# Generated by Django 4.2.15 on 2024-08-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
