# Generated by Django 4.2.15 on 2024-08-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='document',
            field=models.FileField(default='doc', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='document_name',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GrantDocument',
        ),
    ]
